### ISSUE TITLE
Allow multiple selection or adding a folder

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Gallery#8]
Right now, only single file can be added into the app.

**Comment by prokawsar** [comment]
It allows a folder of images to be uploaded. 
Isn't it works for you? 
@kirillt

**Comment by kirillt** [comment]
@prokawsar I remember it worked in your version, but it doesn't work in `main` with Tauri build. I'll double-check in your branch

**Comment by kirillt** [comment]
In Tauri build it doesn't work.

@alvinosh if you have idea why is it so and can fix it, please assign this to yourself.

**Comment by prokawsar** [comment]
@kirillt 
It's working for me as well on tauri build from main branch, tested on Mac.
I guess, it's only for linux issue?

**Comment by kirillt** [comment]
@prokawsar interesting, could be Linux-only issue then.

**Comment by kirillt** [comment]
@alvinosh has Linux for development now. He will continue with this issue.
